---
#
# Install somes programs
#
# invoque with :
# ansible-playbook -i admin.yaml playbooks/thinkpads/030-programs_base.yaml
#
# source : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: Install packages

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: thinkpads

  become: yes

  tasks:
    - name: Install utils packages

      apt:
        name:
            - backintime-qt # sauvegarde
            - btop # moniteur système
            - chromium # web browser
            - dconf-editor # GUI for GNOME desktop environment configuration
            - dupeguru # file duplicates search
            - gnome-logs # lecteur journaux système
            - gnome-tweaks # configuration gnome
            - hyphen-fr # disctionnaire français
            - hunspell-fr # disctionnaire français
            - mint-meta-codecs # codecs additionnels
            - synaptic # gestionnaire de paquets

        state: present

    - name: Install dev packages

      apt:
        name:
            - filezilla # ftp client
            - git-gui # gui for git that installs git
            - meld # comparateur de fichiers / dossiers
            - python3-psutil # needed to manage dconf remotelly with ansible
            - python3-passlib # new crypto lib
            - sublime-merge # git GUI connected to sublime text
            - sublime-text # text editor

        state: present

    - name: Install graphic packages

      apt:
        name:
            - gimp # retouche d'image
            - inkscape # dessin vectoriel
            - krita # retouche d'image
            - scribus # pao

        state: present

    - name: Install audio packages

      apt:
        name:
            - audacity # montage audio

        state: present

    - name: Install video packages

      apt:
        name:
            - blender # montage video
            - obs-studio # montage / regie video
            - openshot-qt # montage video
            - vlc # lecteur multimedia
            - winff # transcodeur vidéo

        state: present


    # interactive installation can be reproduced by ansible with debconf module
    # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/debconf_module.html
    # to see which questions are asked during install use ‘sudo debconf-show <package>’
    - name: prepare interactive answer for iperf3 wich is a hardinfo2 dependency
      debconf:
        name: iperf3
        question: iperf3/start_daemon
        vtype: boolean
        value: false


    - name: Install hardinfo2

      apt:
        name:
            - hardinfo2

        state: present
