---
#
# Install somes programs with flatpack
#
# invoque with :
# ansible-playbook -i admin.yaml playbooks/thinkpads/040-programs_flatpack.yaml
#
# source : https://docs.ansible.com/projects/ansible/latest/collections/community/general/flatpak_module.html

- name: Install packages with flatpack

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: thinkpads

  become: yes

  tasks:
    - name: Install freecad
      flatpak:
        name: org.freecad.FreeCAD

        state: present
