[Authentication]
Method=1

[Core]
ApplicationVersion=2
InstallationID=968109fc-557a-4310-ab0d-7b235a70545f
PluginVersions="@@JsonValue(eyJvIjp7InsxNGJhY2FhYS1lYmU1LTQ0OWMtYjg4MS01YjM4MmY5NTI1NzF9IjoiMS4xIiwiezFiMDgyNjViLTM0OGYtNDk3OC1hY2FhLTQ1ZDRmNmI5MGJkOX0iOiIxLjEiLCJ7MjkxN2NkZWItYWMxMy00MDk5LTg3MTUtMjAzNjgyNTRhMzY3fSI6IjEuMSIsInsyYWQ5OGNjYi1lOWE1LTQzZWYtOGM0Yy04NzZhYzVlZmJjYjF9IjoiMS4xIiwiezM4N2EwYzQzLTEzNTUtNGZmNi05ZTFmLWQwOThlOWNlNTEyN30iOiIxLjEiLCJ7MzlkN2EwN2YtOTRkYi00OTEyLWFhMWEtYzRkZjhhZWUzODc5fSI6IjEuMSIsIns0MTIyZThjYS1iNjE3LTRlMzYtYjg1MS04ZTA1MGVkMmQ4MmV9IjoiMS4yIiwiezQ3OTBiYWQ4LTRjNTYtNDBkNS04MzYxLTA5OWE2OGYwYzI0Yn0iOiIxLjEiLCJ7NjM5MjhhOGEtNGM1MS00YmZkLTg4OGUtOWUxM2M2ZjM5MDdhfSI6IjEuMSIsIns2N2RmYzFjMS04ZjM3LTQ1MzktYTI5OC0xNmU3NGUzNGZkOGJ9IjoiMS4xIiwiezZmMGE0OTFlLWMxYzYtNDMzOC04MjQ0LWY4MjNiMGJmODY3MH0iOiIxLjIiLCJ7ODA1ODA1MDAtMmU1OS00Mjk3LTllMzUtZTUzOTU5YjAyOGNkfSI6IjEuMiIsIns4YWU2NjY4Yi05YzEyLTRiMjktOWJmYy1mZjg5ZjY2MDQxNjR9IjoiMS4xIiwie2E1NGVlMDE4LTQyYmYtNDU2OS05MGM3LTBkODQ3MDEyNWNjZn0iOiIyLjAiLCJ7ZDRiYjljNDItOWVlZi00ZWNiLThkZDUtZGZkODRiMzU1NDgxfSI6IjEuMCIsIntlMTFiZWUwMy1iOTljLTQ2NWMtYmY5MC03ZTUzMzliODNmNmJ9IjoiMS4wIiwie2VlMzIyNTIxLWY0ZmItNDgyZC1iMDgyLTgyYTc5MDAzYWZhN30iOiIxLjEiLCJ7ZjYyNmY3NTktNzY5MS00NWMwLWJkNGEtMzcxNzFkOThkMjE5fSI6IjEuMCJ9fQ==)"

[LDAP]
ComputerLocationAttribute=
ComputerLocationsByAttribute=false
ComputerLocationsByContainer=false
LocationNameAttribute=
UserLoginNameAttribute=

[Master]
AllowAddingHiddenLocations=false
AutoOpenComputerSelectPanel=false
AutoSelectCurrentLocation=false
ConfirmUnsafeActions=false
HideEmptyLocations=false
ShowCurrentLocationOnly=false

[NetworkObjectDirectory]
Plugin=@Variant(\0\0\0\x7f\0\0\0\x6QUuid\0\x14\xba\xca\xaa\xeb\xe5\x44\x9c\xb8\x81[8/\x95%q)

[UserGroups]
Backend=@Variant(\0\0\0\x7f\0\0\0\x6QUuid\0)\x17\xcd\xeb\xac\x13@\x99\x87\x15 6\x82T\xa3g)

[VncServer]
Plugin=@Variant(\0\0\0\x7f\0\0\0\x6QUuid\0\x39\xd7\xa0\x7f\x94\xdbI\x12\xaa\x1a\xc4\xdf\x8a\xee\x38y)
