---
#
# Deploy ssh key for specific user
#
# invoque with :
# ansible-playbook -i playbooks/pc-labo/inventory-admin.yaml playbooks/pc-labo/110-install-php.yaml
#
- name: Install php

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: pc_labo

  become: yes

  vars:
    php_version: "8.4"

  tasks:

    - name: Add Ondrej PHP repository from PPA
      apt_repository:
        repo: ppa:ondrej/php

    - name: Update apt repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: required package and php {{ php_version }}
      apt:
        name:
          - software-properties-common
          - libapache2-mod-fcgid
          - php{{ php_version }}
          - php{{ php_version }}-curl
          - php{{ php_version }}-fpm 
          - php{{ php_version }}-gd 
          - php{{ php_version }}-mbstring 
          - php{{ php_version }}-mysql 
          - php{{ php_version }}-zip 
          - libapache2-mod-php{{ php_version }}

        state: present    


    - name: Enable service php{{ php_version }}-fpm
      service:
        name: php{{ php_version }}-fpm
        enabled: yes

    - name: Enable fcgi
      command: a2enmod actions fcgid alias proxy_fcgi
      notify:
        - restart apache2


  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted            
