---
#
# Read battery level
#
# invoque with :
# ansible-playbook -i playbooks/pc-labo/inventory-admin.yaml playbooks/pc-labo/battery-level.yaml
#
- name: Get battery levels

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: pc_labo
  
  remote_user: utilisateur

  tasks:

    - debug: msg="ansible_user_id = {{ ansible_user_id }}"

    - name: print to stdout
      shell: grep POWER_SUPPLY_CAPACITY /sys/class/power_supply/BAT0/uevent
      register: power

    - debug: msg="{{ power.stdout }}"

    # - debug: msg="OS Version {{ansible_distribution_version}}"

    - name: List files and folder in home directory
      shell: 'ls -l /home'
      register: command_output

    - debug: msg="{{ command_output.stdout_lines }}"
       
    # - name: Check if files are copied
    #   shell: 'ls -l ~/Documents/'
    #   register: command_output

    # - debug: msg="{{ command_output.stdout_lines }}"


    # - name: checking service status
    #   command: systemctl status "{{ item }}"
    #   with_items:
    #     - apache2
    #     - sshd
    #   register: result
    #   ignore_errors: yes

    # - name: showing report
    #   debug:
    #     var: result    


    - name: Get Service Status
      systemd:
        name: "apache2"
      register: pg_service_status




    - debug:
        var: pg_service_status #.status.ActiveState
