---
#
# Allow usb acces to chromium
# used for microbit connection
#
# invoque with :
# ansible-playbook -i admin.yaml playbooks/060-programs_chromium_usb_acces.yaml
#
#
# source : https://docs.ansible.com/ansible/latest/collections/community/general/snap_module.html

- name: Allow usb acces to chromium used for microbit connection

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: hpg32

  become: true

  tasks:
    - name: Snap connect chromium:usb

      # !!!!!!!!!!!!!!!!! NOT WORKING
      # community.general.snap:
      #   name:
      #     - chromium
      #   state: present
      #   options:
      #     - disconnect=raw-usb

      # use shell command instead
      shell:
        cmd: sudo snap connect chromium:raw-usb

    - name: Set rights on USB for Microbit
      copy:
        dest: "/etc/udev/rules.d/50-microbit.rules"
        content: |
          SUBSYSTEM=="usb", ATTR{idVendor}=="0d28", MODE="0664", GROUP="plugdev"

    - name: reload rules
      command: sudo udevadm control --reload-rules
