---
#
# Change password
#
# invoque with :
# ansible-playbook -i admin.yaml playbooks/change-password.yaml

- name: Change password

  vars:

    # reseting admin password
    # username: '{{ ansible_user }}'
    # userpwd: 'Ligue_52'

# OR

    # changing user password
    username: 'invite'
    userpwd: 'a'

  become: yes

  gather_facts: false

# CHANGE THIS IF NECESSARY
#        vvvvvvvv
  hosts: hpg3

  tasks:
    - name: Change user password
      become: yes
      become_method: sudo
      user:
        name: '{{ username }}'
        update_password: always
        password: "{{ userpwd | password_hash('sha512') }}"
